In [4]:
# # Block A — Creation & Inspection (5 tasks)
# Create a 1-D array of the numbers 1 to 20. Print its shape, dtype, size, and
import numpy as np
a=np.arange(5)
print(a)
print("shape=",a.shape)
print("type=",a.dtype)
print("Mean=",a.mean())


[0 1 2 3 4]
shape= (5,)
type= int64
Mean= 2.0


In [12]:
# Create a 5×5 identity matrix and print its sum
import numpy as np
a=np.eye(5)
print("mtraix:",a)
print("sum:",np.sum(a))


mtraix: [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
sum: 5.0


In [17]:
 # Create a 3×4 matrix of zeros and turn the middle column into all 1s
import numpy as np
a=np.zeros((3,4))
a[1]=1
print(a)


[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]]


In [22]:
# Use np.linspace to create 9 evenly spaced points from 0 to 2π. Print them and their sine
# values.
import numpy as np
b=np.linspace(0,2*np.pi,9)
print(b)


[0.         0.78539816 1.57079633 2.35619449 3.14159265 3.92699082
 4.71238898 5.49778714 6.28318531]


In [10]:
# Create a 4×4 matrix of random integers in [0, 100) (seed = 42 for reproducibility) and 
# print its shape, min, max, and mean.
import numpy as np
import random
np.random.seed(42)
a=np.random.randint(0,100,(4,4))
print(a)

print("Minumum:",np.min(a))
print("Maximum",np.max(a))
print("mean:",np.mean(a))
print("shape:",np.shape(a))

[[51 92 14 71]
 [60 20 82 86]
 [74 74 87 99]
 [23  2 21 52]]
Minumum: 2
Maximum 99
mean: 56.75
shape: (4, 4)


In [ ]:
#block B

In [21]:
# 1. Given a = np.arange(20), print: first 5 items, last 3 items, items at even positions, the
# array reversed.
import numpy as np
a=np.arange(20)
print("original array:\n",a)
print("first 5 items:",a[:5])
print("last 3 items:",a[-3::])
print("Even number:",a[(a%2==0)])
print("Array reversed:",a[::-1])
    



original array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
first 5 items: [0 1 2 3 4]
last 3 items: [17 18 19]
Even number: [ 0  2  4  6  8 10 12 14 16 18]
Array reversed: [19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [40]:
# 2. Given a 5×5 matrix of random integers, print: its first row, its last column, its centre 3×3 
# sub-matrix, its main diagonal

import numpy as np
a=np.random.rand(5,5)
a=(a*100).astype(np.int32)
print(a)
print("First row:",a[0])
print("Last colum:",a[:,4])
print("centre 3X3:\n",a[1:4,1:4])#concept of submatrix
print("diagonal:",np.diag(a))# diagnal concept

[[ 0 16 54 69 65]
 [22 71 23 32 74]
 [64 84 65 56  9]
 [36 26 24 97 39]
 [89 63 79 50 57]]
First row: [ 0 16 54 69 65]
Last colum: [65 74  9 39 57]
centre 3X3:
 [[71 23 32]
 [84 65 56]
 [26 24 97]]
diagonal: [ 0 71 65 97 57]


In [44]:
# . Replace every value greater than 50 in a 4×4 random matrix with -1
import numpy as np
a=np.random.randint(1,100,(4,4))
print(a)
a[a>50]=-1
print("new array  element greter than 50:\n",a)

[[67 18 25 95]
 [54 58 67 46]
 [24 32 47 86]
 [23 66 27  2]]
new array  element greter than 50:
 [[-1 18 25 -1]
 [-1 -1 -1 46]
 [24 32 47 -1]
 [23 -1 27  2]]


In [48]:
# Use boolean masking to find and print all values in a = np.arange(100) that are 
# divisible by both 3 and 5

import numpy as np
a=np.arange(100)
print(a)
mask=(a%5==0)&(a%3==0)
print("that elemnt are   divisvle by both 3 and 5:\n",a[mask])


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
that elemnt are   divisvle by both 3 and 5:
 [ 0 15 30 45 60 75 90]


In [57]:
# . Given a 1-D array of scores, use np.where to make a new array where scores < 40 become
# "fail" and the rest become "pass"
import numpy as np
random.seed(42)
a=np.random.randint(30,100,(1,9))
print(a)
result=np.where(a<40,"Fail","pass")
print(result)

[[44 83 89 37 82 89 34 97 35]]
[['pass' 'pass' 'pass' 'Fail' 'pass' 'pass' 'Fail' 'pass' 'Fail']]


In [ ]:
# Block C — Broadcasting (4 tasks

In [68]:
# 1. Create a 4×3 matrix and add a 1-D array of length 3 to every row
import numpy as np
random.seed(42)
a=np.random.randint(30,70,(4,3))
print("new array a 4X3:\n",a)
b=np.random.randint(30,40,(1,3))
print("1D array:",b)
print("addation of  two array:\n",a+b)


new array a 4X3:
 [[50 65 39]
 [66 38 53]
 [64 64 65]
 [47 68 61]]
1D array: [[37 36 34]]
addation of  two array:
 [[ 87 101  73]
 [103  74  87]
 [101 100  99]
 [ 84 104  95]]


In [70]:
# 2. Create a 4×3 matrix and add a column-vector of length 4 to every column.

import numpy as np
random.seed(10)
a=np.random.randint(30,70,(4,3))
print("new array a 4X3:\n",a)
b=np.random.randint(30,40,(4,1))
print("1D array of column:\n",b)
print("addation of  two array:\n",a+b)

new array a 4X3:
 [[41 38 36]
 [57 43 60]
 [48 45 34]
 [64 41 54]]
1D array:
 [[33]
 [34]
 [33]
 [34]]
addation of  two array:
 [[74 71 69]
 [91 77 94]
 [81 78 67]
 [98 75 88]]


In [79]:
# Compute the outer product of two 1-D arrays [1, 2, 3] and [4, 5, 6] using 
# broadcasting (without np.outer).
import numpy as np
a=np.array([1, 2, 3])
b=np.array([4, 5, 6])
result =a[:,None]*b #without using np.outeer Method 1
print("Method 1 result not using np.outer:\n",result)
result1=a.reshape(3,1)*b
print("Method2  result  not using np.outer=\n",result1)


Method 1 result not using np.outer:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Method2  result  not using np.outer=
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [88]:
# . Standardise (subtract mean, divide by std) every column of a 5×4 random matrix
import numpy as np
random.seed(10)
a=np.random.randint(30,70,(5,4))
print(a)
mean=np.mean(a,axis=0)

print("Each and evary column=",mean)
sd=np.std(a,axis=0)#c1,c2, c3  diff rent ising[]c1,c2...c3]
print("Each and every column=",sd)

std=(a-mean)/sd

print("Whole matrix Standardization 0 to 1=\n",std)

[[66 66 39 39]
 [48 46 50 43]
 [38 30 42 33]
 [30 69 61 63]
 [57 60 37 68]]
Each and evary column= [47.8 54.2 45.8 49.2]
Each and every column= [12.87478155 14.4554488   8.79545337 13.77534029]
Whole matrix Standardization 0 to 1=
 [[ 1.41361622  0.81630119 -0.77312672 -0.74045358]
 [ 0.01553424 -0.56726015  0.47751944 -0.45007963]
 [-0.76117796 -1.67410921 -0.4320414  -1.17601451]
 [-1.38254773  1.02383539  1.72816561  1.00179013]
 [ 0.71457523  0.40123279 -1.00051693  1.36475757]]


In [96]:
# Make a 1-D array of 10 evenly spaced values from 0 to 2π. Print sin, cos, and tan for 
# each.
import numpy as np
a=np.array([34,45,67,87,23,12,24,56])
b=np.linspace(0,2*np.pi,10)
print(" All calcu;lation sin:\n",np.sin(b))
print(" all cal culationcos:\n",np.cos(b))
print(" all  CALCULATION Tan:\n",np.tan(b))


 All calcu;lation sin:
 [ 0.00000000e+00  6.42787610e-01  9.84807753e-01  8.66025404e-01
  3.42020143e-01 -3.42020143e-01 -8.66025404e-01 -9.84807753e-01
 -6.42787610e-01 -2.44929360e-16]
 all cal culationcos:
 [ 1.          0.76604444  0.17364818 -0.5        -0.93969262 -0.93969262
 -0.5         0.17364818  0.76604444  1.        ]
 all  CALCULATION Tan:
 [ 0.00000000e+00  8.39099631e-01  5.67128182e+00 -1.73205081e+00
 -3.63970234e-01  3.63970234e-01  1.73205081e+00 -5.67128182e+00
 -8.39099631e-01 -2.44929360e-16]


In [113]:
# . Given x = np.arange(1, 13).reshape(3, 4), find the position (row, col)
x = np.arange(1, 13).reshape(3, 4)
print(x)
print("maximum element:",np.max(x))
print("Maximum elemnt inex:",np.where(x==np.max(x)))#where   find index number




[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
maximum element: 12
Maximum elemnt inex: (array([2]), array([3]))


In [119]:
# 3. For a 1-D array a = np.array([5, 10, 15, 20, 25]), standardise it: (a - 
# mean) / std. Verify the result has mean 0 and std 1.
a = np.array([5, 10, 15, 20, 25])
mean=np.mean(a)
sd=np.std(a)

stad=(a-mean)/sd

print(stad)
print("\nVerification process:\n")

if np.isclose(np.mean(stad), 0) and np.isclose(np.std(stad), 1):
    print("Mean = 0 and Std = 1")
else:
    print("Verification failed")





[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]

Verification process:

Mean = 0 and Std = 1


In [ ]:
#  Compute the dot product of two 1-D arrays of length 5, and the matrix product of two 3×3 
# matrices.
a = [a1, a2, a3]
b = =[b1, b2, b3]
a1b1+a2b2+a3b3

In [121]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.dot(a,b))

32


In [123]:
#  Use np.clip to keep values in a = np.array([-10, -3, 0, 4, 7, 12, 
# 100]) between 0 and 10
a = np.array([-10, -3, 0, 4, 7, 12,100])
print(np.clip(a,0,10))


[ 0  0  0  4  7 10 10]


In [126]:
# . Take an array a = np.arange(24) and reshape it into shapes (2, 12), (3, 8), 
# (4, 6), (2, 3, 4).
a=np.arange(24)
print("reshape (2,12):\n",a.reshape(2,12))
print("reshape (3,8):\n",a.reshape(3,8))
print("reshape (4,6):\n",a.reshape(4,6))
print("reshape (2,3,4):\n",a.reshape(2,3,4))





reshape (2,12):
 [[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]
reshape (3,8):
 [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
reshape (4,6):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
reshape (2,3,4):
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [130]:
# Given two 1-D arrays a and b of length 5, stack them into a 2-row matrix and into a 2-
# column matrix.
import numpy as np
a = np.array([1, 2, 3,8,9])
b = np.array([4, 5, 6,10,11])
print("2- row matrix:\n",np.stack([a,b],axis=0))
print("2- colummatrix\n:",np.stack([a,b],axis=1))




2- row matrix:
 [[ 1  2  3  8  9]
 [ 4  5  6 10 11]]
2- colummatrix
: [[ 1  4]
 [ 2  5]
 [ 3  6]
 [ 8 10]
 [ 9 11]]


In [135]:
# . Split np.arange(20) into 4 equal parts; then concatenate the first and third parts back 
# together.
a=np.arange(20)
parts=np.split(a,4)
for p in parts:
     print(p)

#print(a.reshape(4,1,5)) this is another method



[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [137]:
imgs = np.random.randint(0, 256,size=(8, 32, 32, 3),dtype=np.uint8)
print(imgs)

[[[[189 222 212]
   [ 44  51 193]
   [ 15 253  88]
   ...
   [ 96 204 106]
   [ 17 192  80]
   [  1 104  59]]

  [[181 167 236]
   [ 38 163  75]
   [239  67 224]
   ...
   [151 166  95]
   [211 119 228]
   [188 165   1]]

  [[240 101  95]
   [119 155 160]
   [195 197 216]
   ...
   [172 212 119]
   [204   7  93]
   [250  76 195]]

  ...

  [[ 47  89  78]
   [ 10  41 137]
   [157 178  75]
   ...
   [ 49 231  91]
   [242  12 123]
   [179 219  23]]

  [[ 11  72  22]
   [109 140  64]
   [ 22 105 253]
   ...
   [ 73 157 227]
   [ 97  21 150]
   [110 157  71]]

  [[143  89  12]
   [ 54  13 215]
   [253  84 201]
   ...
   [ 75  26 232]
   [153 194  54]
   [ 93  42 233]]]


 [[[243 251 101]
   [ 39  28  97]
   [ 35 140 147]
   ...
   [ 63  61 163]
   [ 57 164 117]
   [ 71 221 249]]

  [[220  24 132]
   [ 66  99 247]
   [ 69  88  21]
   ...
   [ 27  81  71]
   [161 101   4]
   [110 152  11]]

  [[147  99   4]
   [ 40  86 231]
   [  8 168 125]
   ...
   [ 90 127 241]
   [207 168 162]
   [ 48 253